sample_reviews = [
    "This product is amazing! The quality exceeded my expectations, and it's very durable. I would definitely recommend this to my friends.",
    "I'm not satisfied with this product. It broke after just a week of use. The design is also not as described.",
    "Overall, a decent product for the price. It has a few flaws, but nothing major. The delivery was quick and the customer service was helpful.",
    "Great value for the money. The features are exactly as advertised, and it performs well. I'm happy with my purchase.",
    "The product arrived on time, but it was missing a part. Customer service was responsive and sent the missing part quickly.",
    "Excellent build quality and user-friendly interface. I've been using it for a month now and it works flawlessly.",
    "The color was not exactly what I expected, but the product itself is good. It functions well and serves its purpose.",
    "Too expensive for what it offers. There are better alternatives out there. I wouldn't buy it again.",
    "The packaging was very secure, and the product arrived in perfect condition. It works as advertised.",
    "I've had this for a few weeks now, and so far, I'm impressed with its performance. It's worth the price.",
    "Very disappointed. The product stopped working after a few days. I contacted support, but the response was slow.",
    "A solid product for everyday use. It's not perfect, but it gets the job done. I would consider buying again.",
    "The design is sleek and modern. It fits well in my living room and has received several compliments.",
    "There were some minor scratches on the product when it arrived. However, it works fine, so I'm not too upset.",
    "Great product with excellent features. The instructions were clear and easy to follow, making setup a breeze.",
    "The product is okay, but it doesn't live up to the hype. It's functional, but not outstanding.",
    "The customer service was excellent. They helped me with the setup and answered all my questions promptly.",
    "It's a bit bulky, but it performs well. The price is reasonable for what it offers.",
    "I'm very happy with this purchase. It works exactly as described and has made my life easier.",
    "The product has a few issues, but overall, it's a good buy. The price-performance ratio is fair.",
    "The delivery was delayed, but the product itself is fantastic. It performs as expected and is of high quality.",
    "This is the second time I've bought this product. The first one lasted for years, and I'm confident this one will too.",
    "The setup process was confusing, but once I figured it out, the product worked great.",
    "It's not the best product I've used, but it gets the job done. The price is a bit high for the quality.",
    "Excellent product for the price. It has all the features I need and works well.",
    "I was skeptical at first, but this product has exceeded my expectations. It's reliable and efficient.",
    "The product is lightweight and easy to carry around. It's perfect for travel.",
    "The quality control could be better. My product had a few defects, but nothing that affects functionality.",
    "The product works as advertised, but the battery life is shorter than expected.",
    "I'm impressed with the customer support. They were quick to respond and resolved my issue promptly.",
    "This product is a great addition to my home. It's stylish and functional.",
    "The product was easy to set up and use. It has made my daily routine more convenient.",
    "The quality of materials used is excellent. It feels sturdy and well-made.",
    "I'm not impressed. The product looks cheap and feels flimsy.",
    "The product works, but it's not as good as the reviews suggested. It's okay, but not great.",
    "I've been using this product for a few months now, and it's holding up well. I would recommend it.",
    "The product arrived damaged, but the seller was quick to offer a replacement.",
    "The product is compact and fits easily into small spaces. It's very convenient.",
    "It's a decent product, but I think it's overpriced. There are better options available.",
    "The product met my expectations. It does what it says and is of good quality.",
    "The instructions were unclear, making the setup process difficult. However, the product works well once set up.",
    "This product is a game-changer. It has improved my daily life significantly.",
    "The product is okay, but the customer service is terrible. They were unhelpful and rude.",
    "The product works well, but the design could be improved. It's a bit clunky.",
    "I'm satisfied with this purchase. The product is functional and reliable.",
    "The product is too heavy and difficult to move around. It's not very user-friendly.",
    "The product has a lot of features, but some of them are unnecessary. It's a bit overcomplicated.",
    "This is the best product I've bought in a long time. It's worth every penny.",
    "The product was not as described. It lacks some of the features mentioned in the listing.",
    "The product is easy to use and works as expected. It's a good value for the price."
]
